version: '3'

services:
  vault:
    ports:
      - '3002:3002'
    build:
      context: './'
      dockerfile: './apps/vault/dockerfile'
      target: 'builder'
    command: sh -c "npm run start:vault:dev"
    restart: 'unless-stopped'
    volumes:
      - .:/home/node
      - ./node_modules:/home/node
    env_file:
      - 'apps/vault/development/local.env'
      - 'development/local-base.env'
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
