version: '3'

services:
  vault:
    ports:
      - '3002:3002'
    build:
      context: ./
      dockerfile: './apps/vault/dockerfile'
      target: 'builder'
    command: sh -c "npm run start:vault:dev"
    restart: 'unless-stopped'
    volumes:
      - .:/home/node
      - ./node_modules:/home/node
    env_file:
      - 'apps/vault/development/local.env'
      - 'development/local-base.env'
    networks:
      - backend_network
  heimdall:
    ports:
      - '3003:3003'
    build:
      context: ./
      dockerfile: './apps/heimdall/dockerfile'
      target: 'builder'
    command: sh -c "npm run start:heimdall:dev"
    restart: 'unless-stopped'
    volumes:
      - .:/home/node
      - ./node_modules:/home/node
    env_file:
      - 'apps/heimdall/development/local.env'
      - 'development/local-base.env'
    networks:
      - backend_network
  wolverine:
    ports:
      - '3001:3001'
    build:
      context: ./
      dockerfile: './apps/wolverine/dockerfile'
      target: 'builder'
    command: sh -c "npx prisma migrate dev && npm run start:wolverine:dev"
    restart: 'unless-stopped'
    volumes:
      - .:/home/node
      - ./node_modules:/home/node
    env_file:
      - 'apps/wolverine/development/local.env'
      - 'development/local-base.env'
    networks:
      - backend_network
  denden:
    ports:
      - '3004:3004'
    build:
      context: ./
      dockerfile: './apps/denden/dockerfile'
      target: 'builder'
    command: sh -c "npm run start:denden:dev"
    restart: 'unless-stopped'
    volumes:
      - .:/home/node
      - ./node_modules:/home/node
    env_file:
      - 'apps/denden/development/local.env'
      - 'development/local-base.env'
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
