version: '3'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    restart: unless-stopped
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    environment:
      #      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock # required for localstack×³s lambda service
    networks:
      - backend_network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./development/localstack:/var/lib/localstack"
      - "./development/localstack:/etc/localstack/init/ready.d"
    hostname: localstack
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wolverine
    networks:
      - backend_network
  vault:
    ports:
      - '3002:3002'
    build:
      context: ./
      dockerfile: './apps/vault/dockerfile'
      target: 'builder'
    command: sh -c "npm run start:vault:dev"
    restart: 'unless-stopped'
    volumes:
      - .:/home/node
      - /home/node/node_modules
    env_file:
      - 'apps/vault/development/local.env'
      - 'development/local-base.env'
    depends_on:
      - localstack
    networks:
      - backend_network
  heimdall:
    ports:
      - '3003:3003'
    build:
      context: ./
      dockerfile: './apps/heimdall/dockerfile'
      target: 'builder'
    command: sh -c "npm run start:heimdall:dev"
    restart: 'unless-stopped'
    volumes:
      - .:/home/node
      - /home/node/node_modules
    env_file:
      - 'apps/heimdall/development/local.env'
      - 'development/local-base.env'
    depends_on:
      - localstack
    networks:
      - backend_network
  wolverine:
    ports:
      - '3001:3001'
    build:
      context: ./
      dockerfile: './apps/wolverine/dockerfile'
      target: 'builder'
    command: sh -c "npx prisma generate dev && npx prisma db push && npm run start:wolverine:dev"
    restart: 'unless-stopped'
    volumes:
      - .:/home/node
      - /home/node/node_modules
    env_file:
      - 'apps/wolverine/development/local.env'
      - 'development/local-base.env'
    depends_on:
      - mysql
    networks:
      - backend_network
  denden:
    ports:
      - '3004:3004'
    build:
      context: ./
      dockerfile: './apps/denden/dockerfile'
      target: 'builder'
    command: sh -c "npm run start:denden:dev"
    restart: 'unless-stopped'
    volumes:
      - .:/home/node
      - /home/node/node_modules
    env_file:
      - 'apps/denden/development/local.env'
      - 'development/local-base.env'
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
